[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_liquidator = "S5yb3Bysioeuq7pvuixejRTVfu1kEFUm5gzmkLJL5Dc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
